//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_ISALARY
    {
        public int ID { get; set; }
        public string DBNAME { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string COMPANY { get; set; }
    }
}
