//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LICENSE_MANAGEREntities : DbContext
    {
        public LICENSE_MANAGEREntities()
            : base("name=LICENSE_MANAGEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PRODUCT_KEY> PRODUCT_KEY { get; set; }
        public DbSet<TRAIL_MANAGER> TRAIL_MANAGER { get; set; }
        public DbSet<DB_ISALARY> DB_ISALARY { get; set; }
        public DbSet<MAC_DB> MAC_DB { get; set; }
    }
}
