//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_IS
    {
        public int ID { get; set; }
        public string LOG_RESULT { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
    }
}
