//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAC_DB
    {
        public int ID { get; set; }
        public string MAC { get; set; }
        public Nullable<int> ID_DB { get; set; }
    }
}
