//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_KEY
    {
        public int ID { get; set; }
        public string MAC { get; set; }
        public string LICENSE { get; set; }
        public string COMPANY { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public bool ACTIVE_YN { get; set; }
        public Nullable<System.DateTime> ACTIVE_TIME { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
    }
}
