//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAIL_MANAGER
    {
        public int ID { get; set; }
        public string EMAIL { get; set; }
        public string MAC { get; set; }
        public Nullable<System.DateTime> TRAIL_TIME { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public string COMPANY { get; set; }
        public string PHONE { get; set; }
    }
}
