///************************************************
/// Generated by: haihd
/// Date: 26/06/2016 04:12:33
/// Goal: Create User Service Class for DM_NHAN_VIEN
///************************************************
/// <summary>
/// Create User Service Class for DM_NHAN_VIEN
/// </summary>

using System;
using BKI_DichVuMatDat.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_DichVuMatDat.US{

public class US_DM_NHAN_VIEN : US_Object
{
	private const string c_TableName = "DM_NHAN_VIEN";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strMA_NV 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_NV", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_NV"] = value;
		}
	}

	public bool IsMA_NVNull() 
	{
		return pm_objDR.IsNull("MA_NV");
	}

	public void SetMA_NVNull() {
		pm_objDR["MA_NV"] = System.Convert.DBNull;
	}

	public string strHO_DEM 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "HO_DEM", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["HO_DEM"] = value;
		}
	}

	public bool IsHO_DEMNull() 
	{
		return pm_objDR.IsNull("HO_DEM");
	}

	public void SetHO_DEMNull() {
		pm_objDR["HO_DEM"] = System.Convert.DBNull;
	}

	public string strTEN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN"] = value;
		}
	}

	public bool IsTENNull() 
	{
		return pm_objDR.IsNull("TEN");
	}

	public void SetTENNull() {
		pm_objDR["TEN"] = System.Convert.DBNull;
	}

	public string strEMAIL 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "EMAIL", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["EMAIL"] = value;
		}
	}

	public bool IsEMAILNull() 
	{
		return pm_objDR.IsNull("EMAIL");
	}

	public void SetEMAILNull() {
		pm_objDR["EMAIL"] = System.Convert.DBNull;
	}

	public string strSDT 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "SDT", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["SDT"] = value;
		}
	}

	public bool IsSDTNull() 
	{
		return pm_objDR.IsNull("SDT");
	}

	public void SetSDTNull() {
		pm_objDR["SDT"] = System.Convert.DBNull;
	}

	public DateTime datNGAY_SINH
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "NGAY_SINH", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["NGAY_SINH"] = value;
		}
	}

	public bool IsNGAY_SINHNull()
	{
		return pm_objDR.IsNull("NGAY_SINH");
	}

	public void SetNGAY_SINHNull()
	{
		pm_objDR["NGAY_SINH"] = System.Convert.DBNull;
	}

	public DateTime datNGAY_BAT_DAU_LAM_VIEC
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "NGAY_BAT_DAU_LAM_VIEC", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["NGAY_BAT_DAU_LAM_VIEC"] = value;
		}
	}

	public bool IsNGAY_BAT_DAU_LAM_VIECNull()
	{
		return pm_objDR.IsNull("NGAY_BAT_DAU_LAM_VIEC");
	}

	public void SetNGAY_BAT_DAU_LAM_VIECNull()
	{
		pm_objDR["NGAY_BAT_DAU_LAM_VIEC"] = System.Convert.DBNull;
	}

	public decimal dcLOAI_NHAN_VIEN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "LOAI_NHAN_VIEN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["LOAI_NHAN_VIEN"] = value;
		}
	}

	public bool IsLOAI_NHAN_VIENNull()	{
		return pm_objDR.IsNull("LOAI_NHAN_VIEN");
	}

	public void SetLOAI_NHAN_VIENNull() {
		pm_objDR["LOAI_NHAN_VIEN"] = System.Convert.DBNull;
	}

	public string strPHAI_DONG_DOAN_PHI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "PHAI_DONG_DOAN_PHI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["PHAI_DONG_DOAN_PHI"] = value;
		}
	}

	public bool IsPHAI_DONG_DOAN_PHINull() 
	{
		return pm_objDR.IsNull("PHAI_DONG_DOAN_PHI");
	}

	public void SetPHAI_DONG_DOAN_PHINull() {
		pm_objDR["PHAI_DONG_DOAN_PHI"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_DM_NHAN_VIEN() 
	{
		pm_objDS = new DS_DM_NHAN_VIEN();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_NHAN_VIEN(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_NHAN_VIEN(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_NHAN_VIEN();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
