///************************************************
/// Generated by: haihd
/// Date: 14/07/2016 12:06:28
/// Goal: Create User Service Class for DM_LOAI_NHAN_VIEN
///************************************************
/// <summary>
/// Create User Service Class for DM_LOAI_NHAN_VIEN
/// </summary>

using System;
using BKI_DichVuMatDat.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_DichVuMatDat.US{

public class US_DM_LOAI_NHAN_VIEN : US_Object
{
	private const string c_TableName = "DM_LOAI_NHAN_VIEN";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strMA_LOAI_NHAN_VIEN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_LOAI_NHAN_VIEN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_LOAI_NHAN_VIEN"] = value;
		}
	}

	public bool IsMA_LOAI_NHAN_VIENNull() 
	{
		return pm_objDR.IsNull("MA_LOAI_NHAN_VIEN");
	}

	public void SetMA_LOAI_NHAN_VIENNull() {
		pm_objDR["MA_LOAI_NHAN_VIEN"] = System.Convert.DBNull;
	}

	public string strTEN_LOAI_NHAN_VIEN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_LOAI_NHAN_VIEN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_LOAI_NHAN_VIEN"] = value;
		}
	}

	public bool IsTEN_LOAI_NHAN_VIENNull() 
	{
		return pm_objDR.IsNull("TEN_LOAI_NHAN_VIEN");
	}

	public void SetTEN_LOAI_NHAN_VIENNull() {
		pm_objDR["TEN_LOAI_NHAN_VIEN"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_DM_LOAI_NHAN_VIEN() 
	{
		pm_objDS = new DS_DM_LOAI_NHAN_VIEN();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_LOAI_NHAN_VIEN(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_LOAI_NHAN_VIEN(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_LOAI_NHAN_VIEN();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
