///************************************************
/// Generated by: haihd
/// Date: 25/07/2016 11:50:40
/// Goal: Create User Service Class for DM_PHU_CAP
///************************************************
/// <summary>
/// Create User Service Class for DM_PHU_CAP
/// </summary>

using System;
using BKI_DichVuMatDat.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_DichVuMatDat.US{

public class US_DM_PHU_CAP : US_Object
{
	private const string c_TableName = "DM_PHU_CAP";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strDOI_TUONG_HUONG_PHU_CAP 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DOI_TUONG_HUONG_PHU_CAP", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DOI_TUONG_HUONG_PHU_CAP"] = value;
		}
	}

	public bool IsDOI_TUONG_HUONG_PHU_CAPNull() 
	{
		return pm_objDR.IsNull("DOI_TUONG_HUONG_PHU_CAP");
	}

	public void SetDOI_TUONG_HUONG_PHU_CAPNull() {
		pm_objDR["DOI_TUONG_HUONG_PHU_CAP"] = System.Convert.DBNull;
	}

	public decimal dcTI_LE 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "TI_LE", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["TI_LE"] = value;
		}
	}

	public bool IsTI_LENull()	{
		return pm_objDR.IsNull("TI_LE");
	}

	public void SetTI_LENull() {
		pm_objDR["TI_LE"] = System.Convert.DBNull;
	}

	public string strTI_LE_YN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TI_LE_YN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TI_LE_YN"] = value;
		}
	}

	public bool IsTI_LE_YNNull() 
	{
		return pm_objDR.IsNull("TI_LE_YN");
	}

	public void SetTI_LE_YNNull() {
		pm_objDR["TI_LE_YN"] = System.Convert.DBNull;
	}

	public decimal dcSO_TIEN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "SO_TIEN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["SO_TIEN"] = value;
		}
	}

	public bool IsSO_TIENNull()	{
		return pm_objDR.IsNull("SO_TIEN");
	}

	public void SetSO_TIENNull() {
		pm_objDR["SO_TIEN"] = System.Convert.DBNull;
	}

	public string strDONG_BAO_HIEM_YN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DONG_BAO_HIEM_YN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DONG_BAO_HIEM_YN"] = value;
		}
	}

	public bool IsDONG_BAO_HIEM_YNNull() 
	{
		return pm_objDR.IsNull("DONG_BAO_HIEM_YN");
	}

	public void SetDONG_BAO_HIEM_YNNull() {
		pm_objDR["DONG_BAO_HIEM_YN"] = System.Convert.DBNull;
	}

	public string strGIAM_TRU_THUE_YN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GIAM_TRU_THUE_YN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GIAM_TRU_THUE_YN"] = value;
		}
	}

	public bool IsGIAM_TRU_THUE_YNNull() 
	{
		return pm_objDR.IsNull("GIAM_TRU_THUE_YN");
	}

	public void SetGIAM_TRU_THUE_YNNull() {
		pm_objDR["GIAM_TRU_THUE_YN"] = System.Convert.DBNull;
	}

	public decimal dcID_TIEN_TI_LE_PHU_CAP 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_TIEN_TI_LE_PHU_CAP", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_TIEN_TI_LE_PHU_CAP"] = value;
		}
	}

	public bool IsID_TIEN_TI_LE_PHU_CAPNull()	{
		return pm_objDR.IsNull("ID_TIEN_TI_LE_PHU_CAP");
	}

	public void SetID_TIEN_TI_LE_PHU_CAPNull() {
		pm_objDR["ID_TIEN_TI_LE_PHU_CAP"] = System.Convert.DBNull;
	}

	public string strPHU_THUOC_SO_NGAY_DI_LAM_YN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "PHU_THUOC_SO_NGAY_DI_LAM_YN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["PHU_THUOC_SO_NGAY_DI_LAM_YN"] = value;
		}
	}

	public bool IsPHU_THUOC_SO_NGAY_DI_LAM_YNNull() 
	{
		return pm_objDR.IsNull("PHU_THUOC_SO_NGAY_DI_LAM_YN");
	}

	public void SetPHU_THUOC_SO_NGAY_DI_LAM_YNNull() {
		pm_objDR["PHU_THUOC_SO_NGAY_DI_LAM_YN"] = System.Convert.DBNull;
	}

	public string strMA_PHU_CAP 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_PHU_CAP", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_PHU_CAP"] = value;
		}
	}

	public bool IsMA_PHU_CAPNull() 
	{
		return pm_objDR.IsNull("MA_PHU_CAP");
	}

	public void SetMA_PHU_CAPNull() {
		pm_objDR["MA_PHU_CAP"] = System.Convert.DBNull;
	}

	public string strTEN_PHU_CAP 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_PHU_CAP", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_PHU_CAP"] = value;
		}
	}

	public bool IsTEN_PHU_CAPNull() 
	{
		return pm_objDR.IsNull("TEN_PHU_CAP");
	}

	public void SetTEN_PHU_CAPNull() {
		pm_objDR["TEN_PHU_CAP"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_DM_PHU_CAP() 
	{
		pm_objDS = new DS_DM_PHU_CAP();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_PHU_CAP(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_PHU_CAP(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_PHU_CAP();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
