///************************************************
/// Generated by: haihd
/// Date: 13/07/2016 04:06:34
/// Goal: Create User Service Class for DM_TI_LE_LAM_THEM_THEO_SAN_PHAM
///************************************************
/// <summary>
/// Create User Service Class for DM_TI_LE_LAM_THEM_THEO_SAN_PHAM
/// </summary>

using System;
using BKI_DichVuMatDat.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_DichVuMatDat.US{

public class US_DM_TI_LE_LAM_THEM_THEO_SAN_PHAM : US_Object
{
	private const string c_TableName = "DM_TI_LE_LAM_THEM_THEO_SAN_PHAM";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strMA_LAM_THEM 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_LAM_THEM", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_LAM_THEM"] = value;
		}
	}

	public bool IsMA_LAM_THEMNull() 
	{
		return pm_objDR.IsNull("MA_LAM_THEM");
	}

	public void SetMA_LAM_THEMNull() {
		pm_objDR["MA_LAM_THEM"] = System.Convert.DBNull;
	}

	public decimal dcTI_LE 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "TI_LE", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["TI_LE"] = value;
		}
	}

	public bool IsTI_LENull()	{
		return pm_objDR.IsNull("TI_LE");
	}

	public void SetTI_LENull() {
		pm_objDR["TI_LE"] = System.Convert.DBNull;
	}

	public string strTEN_LOAI_LAM_THEM 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_LOAI_LAM_THEM", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_LOAI_LAM_THEM"] = value;
		}
	}

	public bool IsTEN_LOAI_LAM_THEMNull() 
	{
		return pm_objDR.IsNull("TEN_LOAI_LAM_THEM");
	}

	public void SetTEN_LOAI_LAM_THEMNull() {
		pm_objDR["TEN_LOAI_LAM_THEM"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_DM_TI_LE_LAM_THEM_THEO_SAN_PHAM() 
	{
		pm_objDS = new DS_DM_TI_LE_LAM_THEM_THEO_SAN_PHAM();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_TI_LE_LAM_THEM_THEO_SAN_PHAM(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_TI_LE_LAM_THEM_THEO_SAN_PHAM(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_TI_LE_LAM_THEM_THEO_SAN_PHAM();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
