///************************************************
/// Generated by: haihd
/// Date: 22/08/2016 10:50:40
/// Goal: Create User Service Class for DM_THANG_LUONG_NS
///************************************************
/// <summary>
/// Create User Service Class for DM_THANG_LUONG_NS
/// </summary>

using System;
using BKI_DichVuMatDat.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_DichVuMatDat.US{

public class US_DM_THANG_LUONG_NS : US_Object
{
	private const string c_TableName = "DM_THANG_LUONG_NS";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcID_MA_LNS 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_MA_LNS", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_MA_LNS"] = value;
		}
	}

	public bool IsID_MA_LNSNull()	{
		return pm_objDR.IsNull("ID_MA_LNS");
	}

	public void SetID_MA_LNSNull() {
		pm_objDR["ID_MA_LNS"] = System.Convert.DBNull;
	}

	public decimal dcID_MUC_LNS 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_MUC_LNS", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_MUC_LNS"] = value;
		}
	}

	public bool IsID_MUC_LNSNull()	{
		return pm_objDR.IsNull("ID_MUC_LNS");
	}

	public void SetID_MUC_LNSNull() {
		pm_objDR["ID_MUC_LNS"] = System.Convert.DBNull;
	}

	public decimal dcSO_TIEN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "SO_TIEN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["SO_TIEN"] = value;
		}
	}

	public bool IsSO_TIENNull()	{
		return pm_objDR.IsNull("SO_TIEN");
	}

	public void SetSO_TIENNull() {
		pm_objDR["SO_TIEN"] = System.Convert.DBNull;
	}

	public string strGH_CHU 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GH_CHU", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GH_CHU"] = value;
		}
	}

	public bool IsGH_CHUNull() 
	{
		return pm_objDR.IsNull("GH_CHU");
	}

	public void SetGH_CHUNull() {
		pm_objDR["GH_CHU"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_DM_THANG_LUONG_NS() 
	{
		pm_objDS = new DS_DM_THANG_LUONG_NS();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_THANG_LUONG_NS(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_THANG_LUONG_NS(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_THANG_LUONG_NS();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
