///************************************************
/// Generated by: haihd
/// Date: 10/07/2016 08:43:16
/// Goal: Create User Service Class for GD_CHAM_CONG_LAM_THEM
///************************************************
/// <summary>
/// Create User Service Class for GD_CHAM_CONG_LAM_THEM
/// </summary>

using System;
using BKI_DichVuMatDat.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_DichVuMatDat.US{

public class US_GD_CHAM_CONG_LAM_THEM : US_Object
{
	private const string c_TableName = "GD_CHAM_CONG_LAM_THEM";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcID_NHAN_VIEN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NHAN_VIEN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NHAN_VIEN"] = value;
		}
	}

	public bool IsID_NHAN_VIENNull()	{
		return pm_objDR.IsNull("ID_NHAN_VIEN");
	}

	public void SetID_NHAN_VIENNull() {
		pm_objDR["ID_NHAN_VIEN"] = System.Convert.DBNull;
	}

	public decimal dcID_LOAI_LAM_THEM 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_LAM_THEM", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_LOAI_LAM_THEM"] = value;
		}
	}

	public bool IsID_LOAI_LAM_THEMNull()	{
		return pm_objDR.IsNull("ID_LOAI_LAM_THEM");
	}

	public void SetID_LOAI_LAM_THEMNull() {
		pm_objDR["ID_LOAI_LAM_THEM"] = System.Convert.DBNull;
	}

	public decimal dcSO_GIO_LAM_THEM 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "SO_GIO_LAM_THEM", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["SO_GIO_LAM_THEM"] = value;
		}
	}

	public bool IsSO_GIO_LAM_THEMNull()	{
		return pm_objDR.IsNull("SO_GIO_LAM_THEM");
	}

	public void SetSO_GIO_LAM_THEMNull() {
		pm_objDR["SO_GIO_LAM_THEM"] = System.Convert.DBNull;
	}

	public string strDA_XOA_YN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DA_XOA_YN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DA_XOA_YN"] = value;
		}
	}

	public bool IsDA_XOA_YNNull() 
	{
		return pm_objDR.IsNull("DA_XOA_YN");
	}

	public void SetDA_XOA_YNNull() {
		pm_objDR["DA_XOA_YN"] = System.Convert.DBNull;
	}

	public DateTime datNGAY_CHAM_CONG
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "NGAY_CHAM_CONG", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["NGAY_CHAM_CONG"] = value;
		}
	}

	public bool IsNGAY_CHAM_CONGNull()
	{
		return pm_objDR.IsNull("NGAY_CHAM_CONG");
	}

	public void SetNGAY_CHAM_CONGNull()
	{
		pm_objDR["NGAY_CHAM_CONG"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_GD_CHAM_CONG_LAM_THEM() 
	{
		pm_objDS = new DS_GD_CHAM_CONG_LAM_THEM();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_GD_CHAM_CONG_LAM_THEM(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_GD_CHAM_CONG_LAM_THEM(decimal i_dbID) 
	{
		pm_objDS = new DS_GD_CHAM_CONG_LAM_THEM();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion

    public void xoa_du_lieu_cham_cong(decimal ip_dc_id_nv, string thang, string nam, decimal id_loai_lam_them)
    {

        CStoredProc v_cstore = new CStoredProc("pr_XOA_DU_LIEU_CHAM_CONG_LAM_THEM_THEO_THOI_GIAN");
        v_cstore.addDecimalInputParam("@ID_NHAN_VIEN", ip_dc_id_nv);
        v_cstore.addDecimalInputParam("@THANG", CIPConvert.ToDecimal(thang));
        v_cstore.addDecimalInputParam("@NAM", CIPConvert.ToDecimal(nam));
        v_cstore.addDecimalInputParam("@ID_LOAI_LAM_THEM", id_loai_lam_them);
        v_cstore.ExecuteCommand(this);
    }

    public void FillDatasetChamCongLamThem(DS_GD_CHAM_CONG_LAM_THEM v_ds, string thang, string nam, decimal id_loai_lam_them)
    {
        CStoredProc v_cstore = new CStoredProc("pr_GET_DU_LIEU_CHAM_CONG_LAM_THEM");
        v_cstore.addDecimalInputParam("@thang", CIPConvert.ToDecimal(thang));
        v_cstore.addDecimalInputParam("@nam", CIPConvert.ToDecimal(nam));
        v_cstore.addDecimalInputParam("@id_loai_lam_them", id_loai_lam_them);
        v_cstore.fillDataSetByCommand(this, v_ds);
    }
}
}
