///************************************************
/// Generated by: haihd
/// Date: 25/06/2016 09:49:36
/// Goal: Create User Service Class for GD_LOAI_NV_NGAY_LV_TIEU_CHUAN
///************************************************
/// <summary>
/// Create User Service Class for GD_LOAI_NV_NGAY_LV_TIEU_CHUAN
/// </summary>

using System;
using BKI_DichVuMatDat.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_DichVuMatDat.US{

public class US_GD_LOAI_NV_NGAY_LV_TIEU_CHUAN : US_Object
{
	private const string c_TableName = "GD_LOAI_NV_NGAY_LV_TIEU_CHUAN";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcID_LOAI_NHAN_VIEN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_NHAN_VIEN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_LOAI_NHAN_VIEN"] = value;
		}
	}

	public bool IsID_LOAI_NHAN_VIENNull()	{
		return pm_objDR.IsNull("ID_LOAI_NHAN_VIEN");
	}

	public void SetID_LOAI_NHAN_VIENNull() {
		pm_objDR["ID_LOAI_NHAN_VIEN"] = System.Convert.DBNull;
	}

	public decimal dcTHANG 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "THANG", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["THANG"] = value;
		}
	}

	public bool IsTHANGNull()	{
		return pm_objDR.IsNull("THANG");
	}

	public void SetTHANGNull() {
		pm_objDR["THANG"] = System.Convert.DBNull;
	}

	public decimal dcNAM 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "NAM", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["NAM"] = value;
		}
	}

	public bool IsNAMNull()	{
		return pm_objDR.IsNull("NAM");
	}

	public void SetNAMNull() {
		pm_objDR["NAM"] = System.Convert.DBNull;
	}

	public decimal dcSO_NGAY_LV_TIEU_CHUAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "SO_NGAY_LV_TIEU_CHUAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["SO_NGAY_LV_TIEU_CHUAN"] = value;
		}
	}

	public bool IsSO_NGAY_LV_TIEU_CHUANNull()	{
		return pm_objDR.IsNull("SO_NGAY_LV_TIEU_CHUAN");
	}

	public void SetSO_NGAY_LV_TIEU_CHUANNull() {
		pm_objDR["SO_NGAY_LV_TIEU_CHUAN"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_GD_LOAI_NV_NGAY_LV_TIEU_CHUAN() 
	{
		pm_objDS = new DS_GD_LOAI_NV_NGAY_LV_TIEU_CHUAN();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_GD_LOAI_NV_NGAY_LV_TIEU_CHUAN(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_GD_LOAI_NV_NGAY_LV_TIEU_CHUAN(decimal i_dbID) 
	{
		pm_objDS = new DS_GD_LOAI_NV_NGAY_LV_TIEU_CHUAN();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
