///************************************************
/// Generated by: haihd
/// Date: 03/08/2016 11:30:18
/// Goal: Create User Service Class for RPT_LUONG
///************************************************
/// <summary>
/// Create User Service Class for RPT_LUONG
/// </summary>

using System;
using BKI_DichVuMatDat.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_DichVuMatDat.US{

public class US_RPT_LUONG : US_Object
{
	private const string c_TableName = "RPT_LUONG";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcID_NHAN_VIEN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NHAN_VIEN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NHAN_VIEN"] = value;
		}
	}

	public bool IsID_NHAN_VIENNull()	{
		return pm_objDR.IsNull("ID_NHAN_VIEN");
	}

	public void SetID_NHAN_VIENNull() {
		pm_objDR["ID_NHAN_VIEN"] = System.Convert.DBNull;
	}

	public decimal dcTHANG 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "THANG", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["THANG"] = value;
		}
	}

	public bool IsTHANGNull()	{
		return pm_objDR.IsNull("THANG");
	}

	public void SetTHANGNull() {
		pm_objDR["THANG"] = System.Convert.DBNull;
	}

	public decimal dcNAM 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "NAM", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["NAM"] = value;
		}
	}

	public bool IsNAMNull()	{
		return pm_objDR.IsNull("NAM");
	}

	public void SetNAMNull() {
		pm_objDR["NAM"] = System.Convert.DBNull;
	}

	public string strMA_NV 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_NV", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_NV"] = value;
		}
	}

	public bool IsMA_NVNull() 
	{
		return pm_objDR.IsNull("MA_NV");
	}

	public void SetMA_NVNull() {
		pm_objDR["MA_NV"] = System.Convert.DBNull;
	}

	public string strHO_DEM 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "HO_DEM", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["HO_DEM"] = value;
		}
	}

	public bool IsHO_DEMNull() 
	{
		return pm_objDR.IsNull("HO_DEM");
	}

	public void SetHO_DEMNull() {
		pm_objDR["HO_DEM"] = System.Convert.DBNull;
	}

	public string strTEN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN"] = value;
		}
	}

	public bool IsTENNull() 
	{
		return pm_objDR.IsNull("TEN");
	}

	public void SetTENNull() {
		pm_objDR["TEN"] = System.Convert.DBNull;
	}

	public decimal dcLUONG_NS 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "LUONG_NS", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["LUONG_NS"] = value;
		}
	}

	public bool IsLUONG_NSNull()	{
		return pm_objDR.IsNull("LUONG_NS");
	}

	public void SetLUONG_NSNull() {
		pm_objDR["LUONG_NS"] = System.Convert.DBNull;
	}

	public decimal dcLUONG_CD 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "LUONG_CD", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["LUONG_CD"] = value;
		}
	}

	public bool IsLUONG_CDNull()	{
		return pm_objDR.IsNull("LUONG_CD");
	}

	public void SetLUONG_CDNull() {
		pm_objDR["LUONG_CD"] = System.Convert.DBNull;
	}

	public decimal dcLUONG_NGAY 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "LUONG_NGAY", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["LUONG_NGAY"] = value;
		}
	}

	public bool IsLUONG_NGAYNull()	{
		return pm_objDR.IsNull("LUONG_NGAY");
	}

	public void SetLUONG_NGAYNull() {
		pm_objDR["LUONG_NGAY"] = System.Convert.DBNull;
	}

	public decimal dcLUONG_SAN_PHAM 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "LUONG_SAN_PHAM", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["LUONG_SAN_PHAM"] = value;
		}
	}

	public bool IsLUONG_SAN_PHAMNull()	{
		return pm_objDR.IsNull("LUONG_SAN_PHAM");
	}

	public void SetLUONG_SAN_PHAMNull() {
		pm_objDR["LUONG_SAN_PHAM"] = System.Convert.DBNull;
	}

	public decimal dcLAM_THEM 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "LAM_THEM", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["LAM_THEM"] = value;
		}
	}

	public bool IsLAM_THEMNull()	{
		return pm_objDR.IsNull("LAM_THEM");
	}

	public void SetLAM_THEMNull() {
		pm_objDR["LAM_THEM"] = System.Convert.DBNull;
	}

	public decimal dcLUONG_LAM_THEM_SAN_PHAM 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "LUONG_LAM_THEM_SAN_PHAM", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["LUONG_LAM_THEM_SAN_PHAM"] = value;
		}
	}

	public bool IsLUONG_LAM_THEM_SAN_PHAMNull()	{
		return pm_objDR.IsNull("LUONG_LAM_THEM_SAN_PHAM");
	}

	public void SetLUONG_LAM_THEM_SAN_PHAMNull() {
		pm_objDR["LUONG_LAM_THEM_SAN_PHAM"] = System.Convert.DBNull;
	}

	public decimal dcPHU_CAP 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "PHU_CAP", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["PHU_CAP"] = value;
		}
	}

	public bool IsPHU_CAPNull()	{
		return pm_objDR.IsNull("PHU_CAP");
	}

	public void SetPHU_CAPNull() {
		pm_objDR["PHU_CAP"] = System.Convert.DBNull;
	}

	public decimal dcTHUONG 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "THUONG", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["THUONG"] = value;
		}
	}

	public bool IsTHUONGNull()	{
		return pm_objDR.IsNull("THUONG");
	}

	public void SetTHUONGNull() {
		pm_objDR["THUONG"] = System.Convert.DBNull;
	}

	public decimal dcTRUY_LINH 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "TRUY_LINH", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["TRUY_LINH"] = value;
		}
	}

	public bool IsTRUY_LINHNull()	{
		return pm_objDR.IsNull("TRUY_LINH");
	}

	public void SetTRUY_LINHNull() {
		pm_objDR["TRUY_LINH"] = System.Convert.DBNull;
	}

	public decimal dcTHU_NHAP_KHAC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "THU_NHAP_KHAC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["THU_NHAP_KHAC"] = value;
		}
	}

	public bool IsTHU_NHAP_KHACNull()	{
		return pm_objDR.IsNull("THU_NHAP_KHAC");
	}

	public void SetTHU_NHAP_KHACNull() {
		pm_objDR["THU_NHAP_KHAC"] = System.Convert.DBNull;
	}

	public decimal dcTHU_NHAP 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "THU_NHAP", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["THU_NHAP"] = value;
		}
	}

	public bool IsTHU_NHAPNull()	{
		return pm_objDR.IsNull("THU_NHAP");
	}

	public void SetTHU_NHAPNull() {
		pm_objDR["THU_NHAP"] = System.Convert.DBNull;
	}

	public decimal dcBHXH 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "BHXH", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["BHXH"] = value;
		}
	}

	public bool IsBHXHNull()	{
		return pm_objDR.IsNull("BHXH");
	}

	public void SetBHXHNull() {
		pm_objDR["BHXH"] = System.Convert.DBNull;
	}

	public decimal dcBHYT 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "BHYT", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["BHYT"] = value;
		}
	}

	public bool IsBHYTNull()	{
		return pm_objDR.IsNull("BHYT");
	}

	public void SetBHYTNull() {
		pm_objDR["BHYT"] = System.Convert.DBNull;
	}

	public decimal dcBHTN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "BHTN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["BHTN"] = value;
		}
	}

	public bool IsBHTNNull()	{
		return pm_objDR.IsNull("BHTN");
	}

	public void SetBHTNNull() {
		pm_objDR["BHTN"] = System.Convert.DBNull;
	}

	public decimal dcPHU_THUOC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "PHU_THUOC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["PHU_THUOC"] = value;
		}
	}

	public bool IsPHU_THUOCNull()	{
		return pm_objDR.IsNull("PHU_THUOC");
	}

	public void SetPHU_THUOCNull() {
		pm_objDR["PHU_THUOC"] = System.Convert.DBNull;
	}

	public decimal dcGIA_CANH 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "GIA_CANH", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["GIA_CANH"] = value;
		}
	}

	public bool IsGIA_CANHNull()	{
		return pm_objDR.IsNull("GIA_CANH");
	}

	public void SetGIA_CANHNull() {
		pm_objDR["GIA_CANH"] = System.Convert.DBNull;
	}

	public decimal dcPC_GIAM_TRU_THUE 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "PC_GIAM_TRU_THUE", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["PC_GIAM_TRU_THUE"] = value;
		}
	}

	public bool IsPC_GIAM_TRU_THUENull()	{
		return pm_objDR.IsNull("PC_GIAM_TRU_THUE");
	}

	public void SetPC_GIAM_TRU_THUENull() {
		pm_objDR["PC_GIAM_TRU_THUE"] = System.Convert.DBNull;
	}

	public decimal dcLAM_THEM_GIAM_TRU_THUE 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "LAM_THEM_GIAM_TRU_THUE", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["LAM_THEM_GIAM_TRU_THUE"] = value;
		}
	}

	public bool IsLAM_THEM_GIAM_TRU_THUENull()	{
		return pm_objDR.IsNull("LAM_THEM_GIAM_TRU_THUE");
	}

	public void SetLAM_THEM_GIAM_TRU_THUENull() {
		pm_objDR["LAM_THEM_GIAM_TRU_THUE"] = System.Convert.DBNull;
	}

	public decimal dcLAM_THEM_SAN_PHAM_GIAM_TRU_THUE 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "LAM_THEM_SAN_PHAM_GIAM_TRU_THUE", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["LAM_THEM_SAN_PHAM_GIAM_TRU_THUE"] = value;
		}
	}

	public bool IsLAM_THEM_SAN_PHAM_GIAM_TRU_THUENull()	{
		return pm_objDR.IsNull("LAM_THEM_SAN_PHAM_GIAM_TRU_THUE");
	}

	public void SetLAM_THEM_SAN_PHAM_GIAM_TRU_THUENull() {
		pm_objDR["LAM_THEM_SAN_PHAM_GIAM_TRU_THUE"] = System.Convert.DBNull;
	}

	public decimal dcCAC_LOAI_TIEN_KHAC_GIAM_TRU_THUE 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "CAC_LOAI_TIEN_KHAC_GIAM_TRU_THUE", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["CAC_LOAI_TIEN_KHAC_GIAM_TRU_THUE"] = value;
		}
	}

	public bool IsCAC_LOAI_TIEN_KHAC_GIAM_TRU_THUENull()	{
		return pm_objDR.IsNull("CAC_LOAI_TIEN_KHAC_GIAM_TRU_THUE");
	}

	public void SetCAC_LOAI_TIEN_KHAC_GIAM_TRU_THUENull() {
		pm_objDR["CAC_LOAI_TIEN_KHAC_GIAM_TRU_THUE"] = System.Convert.DBNull;
	}

	public decimal dcGIAM_TRU 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "GIAM_TRU", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["GIAM_TRU"] = value;
		}
	}

	public bool IsGIAM_TRUNull()	{
		return pm_objDR.IsNull("GIAM_TRU");
	}

	public void SetGIAM_TRUNull() {
		pm_objDR["GIAM_TRU"] = System.Convert.DBNull;
	}

	public decimal dcDOAN_PHI_CD 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "DOAN_PHI_CD", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["DOAN_PHI_CD"] = value;
		}
	}

	public bool IsDOAN_PHI_CDNull()	{
		return pm_objDR.IsNull("DOAN_PHI_CD");
	}

	public void SetDOAN_PHI_CDNull() {
		pm_objDR["DOAN_PHI_CD"] = System.Convert.DBNull;
	}

	public decimal dcTHUE 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "THUE", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["THUE"] = value;
		}
	}

	public bool IsTHUENull()	{
		return pm_objDR.IsNull("THUE");
	}

	public void SetTHUENull() {
		pm_objDR["THUE"] = System.Convert.DBNull;
	}

	public decimal dcTRUY_THU 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "TRUY_THU", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["TRUY_THU"] = value;
		}
	}

	public bool IsTRUY_THUNull()	{
		return pm_objDR.IsNull("TRUY_THU");
	}

	public void SetTRUY_THUNull() {
		pm_objDR["TRUY_THU"] = System.Convert.DBNull;
	}

	public decimal dcPHAI_NOP 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "PHAI_NOP", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["PHAI_NOP"] = value;
		}
	}

	public bool IsPHAI_NOPNull()	{
		return pm_objDR.IsNull("PHAI_NOP");
	}

	public void SetPHAI_NOPNull() {
		pm_objDR["PHAI_NOP"] = System.Convert.DBNull;
	}

	public decimal dcPHAI_NOP_KHAC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "PHAI_NOP_KHAC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["PHAI_NOP_KHAC"] = value;
		}
	}

	public bool IsPHAI_NOP_KHACNull()	{
		return pm_objDR.IsNull("PHAI_NOP_KHAC");
	}

	public void SetPHAI_NOP_KHACNull() {
		pm_objDR["PHAI_NOP_KHAC"] = System.Convert.DBNull;
	}

	public decimal dcTHUC_LINH 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "THUC_LINH", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["THUC_LINH"] = value;
		}
	}

	public bool IsTHUC_LINHNull()	{
		return pm_objDR.IsNull("THUC_LINH");
	}

	public void SetTHUC_LINHNull() {
		pm_objDR["THUC_LINH"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_RPT_LUONG() 
	{
		pm_objDS = new DS_RPT_LUONG();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_RPT_LUONG(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_RPT_LUONG(decimal i_dbID) 
	{
		pm_objDS = new DS_RPT_LUONG();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
    public void XoaBangLuongNhanVien(decimal ip_dc_id_nhan_vien, decimal ip_thang, decimal ip_nam)
    {
        CStoredProc v_sp = new CStoredProc("pr_TL_bang_luong_Delete");
        v_sp.addDecimalInputParam("@ip_dc_id_nhan_vien", ip_dc_id_nhan_vien);
        v_sp.addDecimalInputParam("@ip_thang", ip_thang);
        v_sp.addDecimalInputParam("@ip_nam", ip_nam);
        v_sp.ExecuteCommand(this);
    }
#endregion
	}
}
